import 'package:flutter/material.dart';
import 'package:qr_flutter/qr_flutter.dart';
import '../../core/network/api.dart';
import '../../core/notifications/reminders.dart';
import '../../core/theme/preferences.dart';
import '../../core/widgets/clinexa_ui.dart';
import '../auth/login_page.dart';
class AccountPage extends StatefulWidget {
  const AccountPage({super.key});
  @override State<AccountPage> createState()=>_AccountPageState();
}
class _AccountPageState extends State<AccountPage>{
  List<Map<String,dynamic>> sessions=[];bool mfa=false,busy=false;String? error;
  @override void initState(){super.initState();load();}
  Future<void> load()async{try{final r=await Future.wait([Api.dio.get('/api/v1/account/sessions'),Api.dio.get('/api/v1/account/mfa')]);if(mounted)setState((){sessions=List<Map<String,dynamic>>.from(r[0].data);mfa=r[1].data['enabled'];error=null;});}catch(e){if(mounted)setState(()=>error=Api.errorMessage(e));}}
  Future<void> signOut()async{await MedicationReminders.disable();await Api.logout();if(!mounted)return;Navigator.pushAndRemoveUntil(context,MaterialPageRoute(builder:(_)=>LoginPage()),(_)=>false);}
  Future<void> revoke(Map<String,dynamic>? session)async{
    final confirmed=await showDialog<bool>(context:context,builder:(ctx)=>AlertDialog(title:Text(session==null?'Sign out every device?':'Revoke this session?'),content:Text(session==null||session['current']==true?'You will need to sign in again on this device.':'The selected device will lose access immediately.'),actions:[TextButton(onPressed:()=>Navigator.pop(ctx,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(ctx,true),child:const Text('Revoke'))]));if(confirmed!=true)return;
    setState(()=>busy=true);try{if(session==null){await Api.dio.post('/api/v1/account/sessions/revoke-all');}else{await Api.dio.delete('/api/v1/account/sessions/${session['id']}');}if(session==null||session['current']==true){await signOut();}else{await load();}}catch(e){if(mounted)setState(()=>error=Api.errorMessage(e));}finally{if(mounted)setState(()=>busy=false);}
  }
  Future<void> enroll()async{
    final password=TextEditingController();final value=await showDialog<String>(context:context,builder:(ctx)=>AlertDialog(title:const Text('Confirm your password'),content:TextField(controller:password,obscureText:true,decoration:const InputDecoration(labelText:'Current password')),actions:[TextButton(onPressed:()=>Navigator.pop(ctx),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(ctx,password.text),child:const Text('Continue'))]));password.dispose();if(value==null)return;
    try{final r=await Api.dio.post('/api/v1/account/mfa/setup',data:{'password':value});if(!mounted)return;
      final code=TextEditingController();final entered=await showDialog<String>(context:context,builder:(ctx)=>AlertDialog(title:const Text('Set up your authenticator'),content:SizedBox(width:420,child:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[const Text('Scan with your authenticator app, then enter its six-digit code. Enabling MFA signs out existing sessions.'),const SizedBox(height:16),QrImageView(data:r.data['otpauth_url'],size:200,backgroundColor:Colors.white),const SizedBox(height:12),SelectableText(r.data['secret']),const SizedBox(height:16),TextField(controller:code,keyboardType:TextInputType.number,maxLength:6,decoration:const InputDecoration(labelText:'Authenticator code'))]))),actions:[TextButton(onPressed:()=>Navigator.pop(ctx),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(ctx,code.text),child:const Text('Enable MFA'))]));code.dispose();if(entered==null)return;await Api.dio.post('/api/v1/account/mfa/confirm',data:{'code':entered});await signOut();
    }catch(e){if(mounted)setState(()=>error=Api.errorMessage(e));}
  }
  Future<void> disable()async{
    final password=TextEditingController(),code=TextEditingController();
    final data=await showDialog<Map<String,String>>(context:context,builder:(ctx)=>AlertDialog(title:const Text('Disable authenticator MFA'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:password,obscureText:true,decoration:const InputDecoration(labelText:'Password')),const SizedBox(height:12),TextField(controller:code,maxLength:6,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Fresh authenticator code'))]),actions:[TextButton(onPressed:()=>Navigator.pop(ctx),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(ctx,{'password':password.text,'code':code.text}),child:const Text('Disable MFA'))]));password.dispose();code.dispose();if(data==null)return;
    try{await Api.dio.post('/api/v1/account/mfa/disable',data:data);await load();}catch(e){if(mounted)setState(()=>error=Api.errorMessage(e));}
  }
  @override Widget build(BuildContext context)=>SingleChildScrollView(padding:const EdgeInsets.all(24),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[CxPageHeader(eyebrow:'Your account',title:'Make Clinexa yours.',subtitle:'Appearance, accessibility and control over your signed-in devices.'),const SizedBox(height:24),if(error!=null)Padding(padding:const EdgeInsets.only(bottom:16),child:Text(error!,style:TextStyle(color:Theme.of(context).colorScheme.error))),CxAdaptiveGrid(minItemWidth:320,maxColumns:2,children:[CxSurface(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Appearance',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const SizedBox(height:16),ValueListenableBuilder<ThemeMode>(valueListenable:AppPreferences.mode,builder:(ctx,v,_)=>SwitchListTile(contentPadding:EdgeInsets.zero,title:const Text('Dark appearance'),subtitle:const Text('A softer workspace in low light'),value:v==ThemeMode.dark,onChanged:(_)=>AppPreferences.toggleTheme())),ValueListenableBuilder<bool>(valueListenable:AppPreferences.reducedMotion,builder:(ctx,v,_)=>SwitchListTile(contentPadding:EdgeInsets.zero,title:const Text('Reduce motion'),subtitle:const Text('Turn off workspace transition animations'),value:v,onChanged:AppPreferences.setMotion))])),CxSurface(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Icon(Icons.verified_user_outlined,size:34),const SizedBox(height:16),const Text('Authenticator protection',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const SizedBox(height:12),Text(mfa?'MFA is enabled. A fresh authenticator code is required at sign-in.':'Add a six-digit authenticator code to your password.'),const SizedBox(height:20),FilledButton.icon(onPressed:busy?null:mfa?disable:enroll,icon:Icon(mfa?Icons.lock_open:Icons.lock_outline),label:Text(mfa?'Disable MFA':'Set up MFA'))]))]),const SizedBox(height:24),CxSurface(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Expanded(child:Text('Logged-in devices',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold))),IconButton(onPressed:load,tooltip:'Refresh sessions',icon:const Icon(Icons.refresh))]),const SizedBox(height:12),...sessions.map((s)=>ListTile(contentPadding:EdgeInsets.zero,leading:Icon(s['revoked']?Icons.phonelink_erase:Icons.devices),title:Text(s['label'],maxLines:2,overflow:TextOverflow.ellipsis),subtitle:Text('${s['created_at']} · ${s['revoked']?'Revoked':s['current']?'This device':'Active'}'),trailing:s['revoked']?null:IconButton(tooltip:'Revoke session',onPressed:busy?null:()=>revoke(s),icon:const Icon(Icons.logout)))),const SizedBox(height:16),OutlinedButton.icon(onPressed:busy?null:()=>revoke(null),icon:const Icon(Icons.logout),label:const Text('Sign out all devices'))]))]));
}
