import 'dart:convert';
import 'dart:typed_data';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import '../../core/network/api.dart';
import '../../core/widgets/clinexa_ui.dart';
class PrivacyPage extends StatefulWidget{
  const PrivacyPage({super.key});
  @override State<PrivacyPage> createState()=>_PrivacyPageState();
}
class _PrivacyPageState extends State<PrivacyPage>{
  List<Map<String,dynamic>> grants=[],documents=[],access=[];String? error;bool busy=false;
  @override void initState(){super.initState();load();}
  Future<void> load()async{try{final r=await Future.wait([Api.dio.get('/api/v1/privacy/grants'),Api.dio.get('/api/v1/portal/home'),Api.dio.get('/api/v1/privacy/emergency-access')]);if(mounted)setState((){grants=List<Map<String,dynamic>>.from(r[0].data);documents=List<Map<String,dynamic>>.from(r[1].data['documents']);access=List<Map<String,dynamic>>.from(r[2].data);error=null;});}catch(e){if(mounted)setState(()=>error=Api.errorMessage(e));}}
  Future<void> share()async{
    final email=TextEditingController();final scopes=<String>{},ids=<String>{};
    final data=await showDialog<Map<String,dynamic>>(context:context,builder:(ctx)=>StatefulBuilder(builder:(ctx,set)=>AlertDialog(title:const Text('Share with a caregiver'),content:SizedBox(width:500,child:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[const Text('The caregiver must have an account in your hospital. Hospital approval is required before they can read shared information. Access is read-only.'),const SizedBox(height:16),TextField(controller:email,keyboardType:TextInputType.emailAddress,decoration:const InputDecoration(labelText:'Caregiver email')),const SizedBox(height:12),for(final scope in ['appointments','reminders','emergency','selected_documents'])CheckboxListTile(contentPadding:EdgeInsets.zero,title:Text(scope.replaceAll('_',' ')),value:scopes.contains(scope),onChanged:(v)=>set((){if(v==true){scopes.add(scope);}else{scopes.remove(scope);if(scope=='selected_documents')ids.clear();}})),if(scopes.contains('selected_documents'))...documents.map((d)=>CheckboxListTile(title:Text(d['original_name']),subtitle:Text(d['category']),value:ids.contains(d['id']),onChanged:(v)=>set((){if(v==true){ids.add(d['id']);}else{ids.remove(d['id']);}})))]))),actions:[TextButton(onPressed:()=>Navigator.pop(ctx),child:const Text('Cancel')),FilledButton(onPressed:scopes.isEmpty?null:()=>Navigator.pop(ctx,{'email':email.text.trim(),'scopes':scopes.toList(),'document_ids':ids.toList()}),child:const Text('Grant access'))])));
    email.dispose();if(data==null)return;try{await Api.dio.post('/api/v1/privacy/grants',data:data);await load();}catch(e){if(mounted)setState(()=>error=Api.errorMessage(e));}
  }
  Future<void> revoke(Map<String,dynamic> grant)async{
    final yes=await showDialog<bool>(context:context,builder:(ctx)=>AlertDialog(title:const Text('Revoke caregiver access?'),content:Text('${grant['caregiver_name']} will lose access to the shared categories immediately.'),actions:[TextButton(onPressed:()=>Navigator.pop(ctx,false),child:const Text('Keep access')),FilledButton(onPressed:()=>Navigator.pop(ctx,true),child:const Text('Revoke'))]));if(yes!=true)return;
    try{await Api.dio.delete('/api/v1/privacy/grants/${grant['id']}');await load();}catch(e){if(mounted)setState(()=>error=Api.errorMessage(e));}
  }
  Future<void> export()async{setState(()=>busy=true);try{final r=await Api.dio.get('/api/v1/privacy/export');final bytes=Uint8List.fromList(utf8.encode(const JsonEncoder.withIndent('  ').convert(r.data)));await FilePicker.platform.saveFile(dialogTitle:'Save your portal data',fileName:'clinexa_portal_export.json',bytes:bytes,type:FileType.custom,allowedExtensions:['json']);}catch(e){if(mounted)setState(()=>error=Api.errorMessage(e));}finally{if(mounted)setState(()=>busy=false);}}
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Privacy & sharing')),body:SingleChildScrollView(padding:const EdgeInsets.all(24),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[CxPageHeader(eyebrow:'Your information',title:'Shared on your terms.',subtitle:'Choose exactly which categories your caregiver can read. Revoke access whenever you need.',actions:[FilledButton.icon(onPressed:share,icon:const Icon(Icons.person_add_alt),label:const Text('Share access')),OutlinedButton.icon(onPressed:busy?null:export,icon:const Icon(Icons.download_outlined),label:const Text('Export portal data'))]),const SizedBox(height:24),if(error!=null)Text(error!,style:TextStyle(color:Theme.of(context).colorScheme.error)),CxSurface(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Caregiver permissions',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const SizedBox(height:12),if(grants.isEmpty)const Text('You have not shared any access.'),...grants.map((g)=>ListTile(contentPadding:EdgeInsets.zero,leading:Icon(g['revoked']?Icons.person_off_outlined:Icons.person_outline),title:Text(g['caregiver_name']),subtitle:Text('${(g['scopes']as List).join(', ')}\n${g['revoked']?'Revoked':g['approval_status']}'),trailing:g['revoked']?null:TextButton(onPressed:()=>revoke(g),child:const Text('Revoke'))))])),const SizedBox(height:20),CxSurface(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Emergency profile access',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const SizedBox(height:12),if(access.isEmpty)const Text('No emergency scans recorded.'),...access.map((a)=>ListTile(contentPadding:EdgeInsets.zero,leading:const Icon(Icons.health_and_safety_outlined),title:Text(a['access_type']),subtitle:Text('${a['accessed_at']} · ${a['source']??'Token scan'}')))])),const SizedBox(height:12),const Text('Portal export includes the data shown in your portal, including appointments, medicines, labs and document metadata. It does not include the document files or every hospital record.')] )));
}
