"""Frozen 0002_v9 schema migration."""
from alembic import op
import sqlalchemy as sa
revision='0002_v9'
down_revision='0001_v8'
branch_labels=None
depends_on=None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_background_jobs_state'), 'background_jobs', ['state'], unique=False)
    op.create_table('caregiver_grants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('caregiver_id', sa.String(length=36), nullable=False),
    sa.Column('granted_by', sa.String(length=36), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'caregiver_id')
    )
    op.create_index(op.f('ix_caregiver_grants_patient_id'), 'caregiver_grants', ['patient_id'], unique=False)
    op.create_table('clinical_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_drafts_hospital_id'), 'clinical_drafts', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_clinical_drafts_patient_id'), 'clinical_drafts', ['patient_id'], unique=False)
    op.create_table('clinical_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_type', 'resource_id', 'version')
    )
    op.create_index(op.f('ix_clinical_revisions_hospital_id'), 'clinical_revisions', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_clinical_revisions_resource_id'), 'clinical_revisions', ['resource_id'], unique=False)
    op.create_table('device_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_id')
    )
    op.create_index(op.f('ix_device_sessions_user_id'), 'device_sessions', ['user_id'], unique=False)
    op.create_table('mfa_factors',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('encrypted_secret', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_counter', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('enabled_categories', sa.Text(), nullable=False),
    sa.Column('muted_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('recovery_tickets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('workspace_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_records_hospital_id'), 'workspace_records', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_workspace_records_kind'), 'workspace_records', ['kind'], unique=False)
    op.create_index(op.f('ix_workspace_records_patient_id'), 'workspace_records', ['patient_id'], unique=False)
    op.create_table('dose_receipts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('dose_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['dose_id'], ['medication_dose_logs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dose_id')
    )
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == 'sqlite':
        op.execute("CREATE TRIGGER IF NOT EXISTS clinical_revision_no_update BEFORE UPDATE ON clinical_revisions BEGIN SELECT RAISE(ABORT, 'Clinical revisions are append-only'); END")
        op.execute("CREATE TRIGGER IF NOT EXISTS clinical_revision_no_delete BEFORE DELETE ON clinical_revisions BEGIN SELECT RAISE(ABORT, 'Clinical revisions are append-only'); END")
    elif op.get_bind().dialect.name == 'postgresql':
        op.execute("CREATE OR REPLACE FUNCTION clinexa_revision_immutable() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'Clinical revisions are append-only'; END; $$ LANGUAGE plpgsql")
        op.execute("CREATE TRIGGER clinical_revision_immutable BEFORE UPDATE OR DELETE ON clinical_revisions FOR EACH ROW EXECUTE FUNCTION clinexa_revision_immutable()")


def downgrade():
    raise RuntimeError("Automatic downgrade is disabled to protect clinical records. Restore a verified backup instead.")
