import 'dart:convert';
import 'dart:typed_data';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import '../../core/network/api.dart';
import '../../core/widgets/clinexa_ui.dart';
class AuditPage extends StatefulWidget{
  const AuditPage({super.key});
  @override State<AuditPage> createState()=>_AuditPageState();
}
class _AuditPageState extends State<AuditPage>{
  List<Map<String,dynamic>> rows=[];final action=TextEditingController(),actor=TextEditingController(),resource=TextEditingController();DateTime? since,until;String? error;bool loading=false;
  @override void initState(){super.initState();load();}
  @override void dispose(){action.dispose();actor.dispose();resource.dispose();super.dispose();}
  Future<void> load()async{setState(()=>loading=true);try{final r=await Api.dio.get('/api/v1/admin/audit',queryParameters:{'limit':500,if(action.text.isNotEmpty)'action':action.text,if(actor.text.isNotEmpty)'actor_id':actor.text,if(resource.text.isNotEmpty)'resource':resource.text,if(since!=null)'since':since!.toUtc().toIso8601String(),if(until!=null)'until':until!.add(const Duration(days:1)).toUtc().toIso8601String()});if(mounted)setState((){rows=List<Map<String,dynamic>>.from(r.data);error=null;});}catch(e){if(mounted)setState(()=>error=Api.errorMessage(e));}finally{if(mounted)setState(()=>loading=false);}}
  Future<void> date(bool start)async{final d=await showDatePicker(context:context,initialDate:(start?since:until)??DateTime.now(),firstDate:DateTime(2020),lastDate:DateTime.now());if(d!=null)setState((){if(start){since=d;}else{until=d;}});}
  String csvCell(dynamic value){var s=value?.toString()??'';if(RegExp(r'^[=+@-]').hasMatch(s))s="'$s";return '"${s.replaceAll('"','""')}"';}
  Future<void> export()async{try{const cols=['created_at','actor_name','actor_user_id','action','resource','resource_id','result'];final csv=[cols.join(','),...rows.map((r)=>cols.map((k)=>csvCell(r[k])).join(','))].join('\r\n');await FilePicker.platform.saveFile(fileName:'clinexa_audit.csv',bytes:Uint8List.fromList(utf8.encode(csv)),type:FileType.custom,allowedExtensions:['csv']);}catch(e){if(mounted)setState(()=>error=Api.errorMessage(e));}}
  void details(Map<String,dynamic> row){showDialog(context:context,builder:(ctx)=>AlertDialog(title:Text(row['action']),content:ConstrainedBox(constraints:const BoxConstraints(maxWidth:650),child:SingleChildScrollView(child:SelectableText(const JsonEncoder.withIndent('  ').convert(row)))),actions:[TextButton(onPressed:()=>Navigator.pop(ctx),child:const Text('Close'))]));}
  @override Widget build(BuildContext context)=>SingleChildScrollView(padding:const EdgeInsets.all(24),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[CxPageHeader(eyebrow:'Governance',title:'A clear trail of activity.',subtitle:'Search events associated with users in your hospital. Exports include up to 500 matching events.',actions:[OutlinedButton.icon(onPressed:export,icon:const Icon(Icons.download_outlined),label:const Text('Export CSV'))]),const SizedBox(height:24),CxSurface(child:Column(children:[CxAdaptiveGrid(maxColumns:3,children:[TextField(controller:action,decoration:const InputDecoration(labelText:'Action contains')),TextField(controller:actor,decoration:const InputDecoration(labelText:'Actor ID')),TextField(controller:resource,decoration:const InputDecoration(labelText:'Object type'))]),const SizedBox(height:16),Wrap(spacing:10,runSpacing:10,children:[OutlinedButton.icon(onPressed:()=>date(true),icon:const Icon(Icons.calendar_today),label:Text(since==null?'From date':since!.toIso8601String().split('T').first)),OutlinedButton.icon(onPressed:()=>date(false),icon:const Icon(Icons.calendar_today),label:Text(until==null?'Through date':until!.toIso8601String().split('T').first)),FilledButton.icon(onPressed:loading?null:load,icon:const Icon(Icons.search),label:const Text('Apply filters')),TextButton(onPressed:(){action.clear();actor.clear();resource.clear();setState((){since=null;until=null;});load();},child:const Text('Reset'))])])),const SizedBox(height:20),if(error!=null)Text(error!,style:TextStyle(color:Theme.of(context).colorScheme.error)),if(loading)const Center(child:CircularProgressIndicator())else CxSurface(child:Column(children:[if(rows.isEmpty)const Text('No matching audit events.'),...rows.map((r)=>ListTile(contentPadding:EdgeInsets.zero,leading:const Icon(Icons.history),title:Text(r['action']),subtitle:Text('${r['actor_name']} · ${r['created_at']}\n${r['resource']} · ${r['resource_id']??''}'),trailing:const Icon(Icons.chevron_right),onTap:()=>details(r)))]))]));
}
