import 'package:flutter/material.dart';
import 'package:qr_flutter/qr_flutter.dart';
import '../../core/network/api.dart';
import '../../core/widgets/clinexa_ui.dart';
class LabWorkspacePage extends StatefulWidget {
  const LabWorkspacePage({super.key});
  @override State<LabWorkspacePage> createState()=>_LabWorkspacePageState();
}
class _LabWorkspacePageState extends State<LabWorkspacePage> {
  List<Map<String,dynamic>> rows=[],patients=[];
  String filter='all';String? error;bool loading=true,busy=false;
  final transitions=<String,List<String>>{'ordered':['collected','cancelled'],'collected':['received','rejected'],'received':['processing','rejected'],'processing':['technician_verified','rejected'],'technician_verified':['doctor_reviewed'],'doctor_reviewed':['released'],'released':[],'cancelled':[],'rejected':[]};
  @override void initState(){super.initState();load();}
  Future<void> load()async{try{final r=await Future.wait([Api.dio.get('/api/v1/lab-workspace/specimens'),Api.dio.get('/api/v1/patients')]);if(mounted)setState((){rows=List<Map<String,dynamic>>.from(r[0].data);patients=List<Map<String,dynamic>>.from(r[1].data);loading=false;error=null;});}catch(e){if(mounted)setState((){error=Api.errorMessage(e);loading=false;});}}
  Future<void> create()async{
    String? patient;final test=TextEditingController(),specimen=TextEditingController();
    final data=await showDialog<Map<String,dynamic>>(context:context,builder:(ctx)=>StatefulBuilder(builder:(ctx,set)=>AlertDialog(title:const Text('Order a specimen'),content:ConstrainedBox(constraints:const BoxConstraints(maxWidth:420),child:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField<String>(isExpanded:true,items:patients.map((p)=>DropdownMenuItem(value:p['id'].toString(),child:Text(p['full_name']))).toList(),onChanged:(v)=>set(()=>patient=v),decoration:const InputDecoration(labelText:'Patient')),const SizedBox(height:12),TextField(controller:test,decoration:const InputDecoration(labelText:'Requested test')),const SizedBox(height:12),TextField(controller:specimen,decoration:const InputDecoration(labelText:'Specimen type'))])),actions:[TextButton(onPressed:()=>Navigator.pop(ctx),child:const Text('Cancel')),FilledButton(onPressed:patient==null?null:()=>Navigator.pop(ctx,{'patient_id':patient,'test_name':test.text,'specimen':specimen.text}),child:const Text('Create order'))])));
    test.dispose();specimen.dispose();if(data==null)return;
    await run(()=>Api.dio.post('/api/v1/lab-workspace/specimens',data:data));
  }
  Future<void> run(Future<dynamic> Function() action)async{setState(()=>busy=true);try{await action();await load();}catch(e){if(mounted)setState(()=>error=Api.errorMessage(e));}finally{if(mounted)setState(()=>busy=false);}}
  Future<void> stage(Map<String,dynamic> row,String state)async{
    final note=TextEditingController();
    final confirmed=await showDialog<bool>(context:context,builder:(ctx)=>AlertDialog(title:Text('Move to ${state.replaceAll('_',' ')}?'),content:Column(mainAxisSize:MainAxisSize.min,children:[Text(state=='released'?'This publishes the manually verified results to the patient record.':'${row['patient_name']} · ${row['test_name']}'),const SizedBox(height:16),TextField(controller:note,maxLines:3,decoration:InputDecoration(labelText:state=='rejected'?'Rejection reason (required)':'Workflow note'))]),actions:[TextButton(onPressed:()=>Navigator.pop(ctx,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(ctx,true),child:const Text('Confirm'))]));
    final reason=note.text;note.dispose();if(confirmed!=true)return;
    await run(()=>Api.dio.patch('/api/v1/lab-workspace/specimens/${row['id']}/stage',data:{'version':row['version'],'state':state,'note':reason}));
  }
  Future<void> verify(Map<String,dynamic> row)async{
    final fields=await showDialog<List<Map<String,dynamic>>>(context:context,builder:(ctx)=>_LabVerifier(initial:List<Map<String,dynamic>>.from(row['fields']??[])));
    if(fields==null)return;
    await run(()=>Api.dio.post('/api/v1/lab-workspace/specimens/${row['id']}/verify',data:{'version':row['version'],'confirmed':true,'fields':fields}));
  }
  void details(Map<String,dynamic> row){showDialog(context:context,builder:(ctx)=>Dialog(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:620),child:ListView(shrinkWrap:true,padding:const EdgeInsets.all(24),children:[Text(row['patient_name'],style:const TextStyle(fontSize:24,fontWeight:FontWeight.bold)),const SizedBox(height:12),SelectableText(row['accession_number']),Center(child:QrImageView(data:row['accession_number'],size:150,backgroundColor:Colors.white)),const Text('Accession QR · scan to identify this specimen'),const Divider(height:32),...(row['timeline']as List).map((e)=>ListTile(leading:const Icon(Icons.circle,size:12),title:Text(e['state'].toString().replaceAll('_',' ')),subtitle:Text('${e['at']}\n${e['note']}'))),TextButton(onPressed:()=>Navigator.pop(ctx),child:const Text('Close'))]))));}
  @override Widget build(BuildContext context){
    final visible=rows.where((r)=>filter=='all'||r['state']==filter).toList();
    return SingleChildScrollView(padding:const EdgeInsets.all(24),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[CxPageHeader(eyebrow:'Laboratory',title:'Every specimen, accounted for.',subtitle:'Track collection, processing and verification through to patient release.',actions:[if(Api.can('lab.orders.manage'))FilledButton.icon(onPressed:busy?null:create,icon:const Icon(Icons.add),label:const Text('New specimen')),IconButton(onPressed:load,tooltip:'Refresh',icon:const Icon(Icons.refresh))]),const SizedBox(height:24),Wrap(spacing:8,runSpacing:8,children:['all',...transitions.keys].map((s)=>FilterChip(label:Text(s.replaceAll('_',' ')),selected:filter==s,onSelected:(_)=>setState(()=>filter=s))).toList()),const SizedBox(height:20),if(error!=null)Text(error!,style:TextStyle(color:Theme.of(context).colorScheme.error)),if(loading)const Center(child:CircularProgressIndicator())else if(visible.isEmpty)CxSurface(child:const Text('No specimens in this stage.'))else CxAdaptiveGrid(minItemWidth:330,maxColumns:3,children:visible.map((r)=>CxSurface(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(r['patient_name'],style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold))),Chip(label:Text(r['state'].toString().replaceAll('_',' ')))]),const SizedBox(height:10),Text(r['test_name'],style:const TextStyle(fontSize:20,fontWeight:FontWeight.w600)),const SizedBox(height:8),Text('${r['specimen']} · ${(r['fields'] as List).length} verified fields'),const SizedBox(height:12),Text(r['accession_number'],style:Theme.of(context).textTheme.bodySmall),const SizedBox(height:16),Wrap(spacing:6,runSpacing:6,children:[TextButton.icon(onPressed:()=>details(r),icon:const Icon(Icons.qr_code),label:const Text('Tracking')),if(Api.can('lab_results.upload')&&r['state']=='processing')OutlinedButton.icon(onPressed:busy?null:()=>verify(r),icon:const Icon(Icons.fact_check_outlined),label:const Text('Verify results')),if(Api.can('lab.orders.manage'))...transitions[r['state']]!.map((s)=>TextButton(onPressed:busy?null:()=>stage(r,s),child:Text(s.replaceAll('_',' '))))])]))).toList())]));
  }
}
class _LabVerifier extends StatefulWidget{
  final List<Map<String,dynamic>> initial;
  const _LabVerifier({required this.initial});
  @override State<_LabVerifier> createState()=>_LabVerifierState();
}
class _LabVerifierState extends State<_LabVerifier>{
  final source=TextEditingController();List<Map<String,dynamic>> fields=[];bool confirmed=false,parsing=false;String? error;
  @override void initState(){super.initState();fields=widget.initial.map((f)=>Map<String,dynamic>.from(f)).toList();}
  @override void dispose(){source.dispose();super.dispose();}
  Future<void> parse()async{setState(()=>parsing=true);try{final r=await Api.dio.post('/api/v1/lab-workspace/parse',data:{'text':source.text});if(mounted)setState((){fields=List<Map<String,dynamic>>.from(r.data['fields']);confirmed=false;error=fields.isEmpty?'No rows parsed. Enter fields manually and compare with the report.':'Review every field. ${(r.data['unparsed_lines']as List).length} source lines were not parsed.';});}catch(e){if(mounted)setState(()=>error=Api.errorMessage(e));}finally{if(mounted)setState(()=>parsing=false);}}
  Widget editor()=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Verify each field',style:TextStyle(fontWeight:FontWeight.bold,fontSize:18)),if(error!=null)Padding(padding:const EdgeInsets.symmetric(vertical:10),child:Text(error!)),for(var i=0;i<fields.length;i++)Padding(padding:const EdgeInsets.only(bottom:16),child:Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(children:[if(fields[i]['source']!=null)Text('Source: ${fields[i]['source']}',style:Theme.of(context).textTheme.bodySmall),for(final key in ['test_name','result_value','unit','reference_range'])Padding(padding:const EdgeInsets.only(top:8),child:TextFormField(key:ValueKey('$i-$key-${fields[i]['source']}'),initialValue:fields[i][key]?.toString()??'',decoration:InputDecoration(labelText:key.replaceAll('_',' '),helperText:fields[i]['confidence'] is Map?'Parsing confidence: ${((fields[i]['confidence'][key]??0)*100).round()}%':null),onChanged:(v){fields[i][key]=v;setState(()=>confirmed=false);})),TextButton.icon(onPressed:()=>setState((){fields.removeAt(i);confirmed=false;}),icon:const Icon(Icons.delete_outline),label:const Text('Remove field'))])))),OutlinedButton.icon(onPressed:()=>setState((){fields.add({'test_name':'','result_value':'','unit':'','reference_range':''});confirmed=false;}),icon:const Icon(Icons.add),label:const Text('Add test manually'))]);
  @override Widget build(BuildContext context)=>Dialog(child:ConstrainedBox(constraints:BoxConstraints(maxWidth:1100,maxHeight:MediaQuery.sizeOf(context).height*.9),child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Lab report verification',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold)),const SizedBox(height:16),LayoutBuilder(builder:(ctx,c){final text=Column(children:[TextField(controller:source,minLines:10,maxLines:24,decoration:const InputDecoration(labelText:'Source report text',hintText:'Paste document OCR text or enter report rows. Use two spaces between test and value.',alignLabelWithHint:true)),const SizedBox(height:12),FilledButton.icon(onPressed:parsing?null:parse,icon:const Icon(Icons.document_scanner_outlined),label:Text(parsing?'Parsing…':'Parse source'))]);return c.maxWidth>=760?Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(child:text),const SizedBox(width:24),Expanded(child:editor())]):Column(children:[text,const SizedBox(height:24),editor()]);}),const SizedBox(height:16),CheckboxListTile(contentPadding:EdgeInsets.zero,value:confirmed,onChanged:(v)=>setState(()=>confirmed=v??false),title:const Text('I checked every result, unit and range against the source report.')),Wrap(spacing:12,children:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Cancel')),FilledButton(onPressed:!confirmed||fields.isEmpty?null:()=>Navigator.pop(context,fields.map((f)=>{for(final k in ['test_name','result_value','unit','reference_range'])k:f[k]?.toString()??''}).toList()),child:const Text('Save verified fields'))])]))));
}
